@startuml
left to right direction

package "RentalCarBooking" {

    class "<<Application>>\nRentalCarService" as RentalCarService {}

    class "<<Resource>>\nUsers" as ResourceUsers {
        <<GET>> +getUsers(): User
        <<POST>> +createUser(): User
    }

    class "<<Resource>>\nUser" as ResourceUser {
        <<GET>> +getUser(): User
        <<PUT>> +updateUser(): User
        <<DELETE>> +deleteUser(): void
        <<POST>> +login(): User
        <<POST>> +logout(): void
    }

    class "<<Resource>>\nCarProviders" as ResourceCarProviders {
        <<GET>> +getCarProviders(): CarProvider
        <<POST>> +createCarProvider(): CarProvider
    }

    class "<<Resource>>\nCarProvider" as ResourceCarProvider {
        <<GET>> +getCarProvider(): CarProvider
        <<PUT>> +updateCarProvider(): CarProvider
        <<DELETE>> +deleteCarProvider(): void
    }

    class "<<Resource>>\nBookings" as ResourceBookings {
        <<GET>> +getBookings(): Booking
        <<POST>> +createBooking(): Booking
    }

    class "<<Representation>>\nUser" as RepresentationUser {
        - name: String
        - email: String
        - tel: String
        - role: String
        - password: String
        - resetPasswordToken: String
        - resetPasswordExpire: Date
        - createAt: Date
    }

    class "<<Representation>>\nCarProvider" as RepresentationCarProvider {
        - name: String
        - address: String
        - district: String
        - province: String
        - postalcode: String
        - tel: String
    }

    class "<<Representation>>\nBooking" as RepresentationBooking {
        - startDate: Date
        - endDate: Date
        - user: User
        - carProvider: CarProvider
        - createdAt: Date
    }
}

RentalCarService ..> ResourceUsers: "/users\n<<Path>>"
ResourceUsers ..> ResourceUser: "/{userId}\n<<Path>>"
ResourceUser ..> RepresentationUser: "<<use>>"
ResourceUser ..> login: "<<login>>"
ResourceUser ..> logout: "<<logout>>"

RentalCarService ..> ResourceCarProviders: "/carproviders\n<<Path>>"
ResourceCarProviders ..> ResourceCarProvider: "/{carProviderId}\n<<Path>>"
ResourceCarProvider ..> RepresentationCarProvider: "<<use>>"

RentalCarService ..> ResourceBookings: "/bookings\n<<Path>>"
ResourceBookings ..> RepresentationBooking: "<<use>>"
RepresentationBooking -> RepresentationUser: "user"
RepresentationBooking -> RepresentationCarProvider: "carProvider"

RepresentationUser "1" <---> "*" RepresentationBooking : "booking"
RepresentationCarProvider "1" <---> "*" RepresentationBooking : "booking (Cascade Delete)"
@enduml